/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DefineModel: typeof import('./src/components/DefineModel.vue')['default']
    DefineProps: typeof import('./src/components/DefineProps.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
