/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefineModels: typeof import('./src/components/DefineModels.vue')['default']
    DefineProps: typeof import('./src/components/DefineProps.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
